//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: MapScan_.h
//  Source: ssafy_msgs\msg\MapScan_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice 6.9.190403OSS
//  
//******************************************************************
#ifndef _MAPSCAN__H_
#define _MAPSCAN__H_

#include "sacpp_mapping.h"
#include "ssafy_msgs/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"


namespace ssafy_msgs
{
   namespace msg
   {
      namespace dds_
      {
         struct MapScan_;

         struct ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_ssafy_msgs MapScan_
         {
               DDS::Long run_;
         };

         typedef DDS_DCPSStruct_var < MapScan_> MapScan__var;
         typedef MapScan_&MapScan__out;
      }
   }
}




#endif
